package com.sfep.equipmentmonitor.risk;

public enum ReasonCode {
    NONE, LOW_SUPPORT, LOW_DEFECT_COUNT, ZERO_COMPARATOR_RISK, NON_FINITE_ESTIMATE,
    NO_INFORMATIVE_STRATA, NO_VARIATION, ZERO_VARIANCE, DIRECTION_NOT_REPEATED,
    TOO_FEW_VALID_BOOTSTRAPS, NOT_APPLICABLE
}
